### ISSUE TITLE
关于Layer#handle_method

### ISSUE THREAD

**Issue by yjhmelody** [sunkuo/grow-to-express#1]
this.method 应该不需要`toLowerCase`函数
因为 methods 库已经放的是http方法的小写单词了

请问不知道您这样写是什么用意？

**Comment by sunkuo** [comment]
@yjhmelody 请问你说的是哪一节的代码？

**Comment by yjhmelody** [comment]
@sunkuo  第二节的 Layer的方法

**Comment by sunkuo** [comment]
@yjhmelody 是的，应该不需要加toLowerCase

**Comment by sunkuo** [comment]
@yjhmelody 加上的话，会更严谨一些

**Comment by sunkuo** [comment]
@yjhmelody 你可以提个PR

**Comment by yjhmelody** [comment]
@sunkuo 还是加上吧，我觉得确实这样更严谨。
话说该文章还没有更新完吧？express大概写到什么程度？

**Comment by sunkuo** [comment]
更新基本完了，还有一些零碎的，不影响整体理解。你可以看下express源码，应该很容易理解了
