### ISSUE TITLE
第三章proto.handle方法

### ISSUE THREAD

**Issue by yjhmelody** [sunkuo/grow-to-express#2]
```js
this.route.dispatch.apply(this.route, slice.call(arguments))
this.route.dispatch(arguments)
```
这两种写法应该等价的为什么要用上面那种？
* 为什么需要浅拷贝arguments ？ 
* dispatch的this指向的难道不就是route吗？

**Comment by sunkuo** [comment]
1.arguments并不是数组，用slice将他转化为数组
2.在这个情况下this是指向route，这样写是一种编程习惯
