### ISSUE TITLE
关于Lesson3跳到Lesson4的疑问

### ISSUE THREAD

**Issue by shenjo** [sunkuo/grow-to-express#3]
跟着Lesson一路写下来：到Lesson3时，写的代码大致差不多。（只不过我用了更多es6语法而已，无伤大雅）但到Lesson4的时候，第一感觉就是博主实现的是不是过于臃肿了？（没有看express源码，有这样的疑问），不就是跟Lesson3一样，只不过引入了path进来了吗？于是我只改了有关path的部分，也能跑起来。
我的Lesson3: https://github.com/shenjo/express-study/blob/master/src/router.js
Router.js 
![image](https://user-images.githubusercontent.com/13912646/33751702-a8a2d282-dc17-11e7-81a2-b0ad0b98b613.png)
Lesson 4 Router.js(还没提交到github上）
![image](https://user-images.githubusercontent.com/13912646/33751756-feee6fe8-dc17-11e7-9b87-5174844eb120.png)
区别在与使用时，app.get('/',fn1,fn2) 第一个参数都是path了，后续的参数才是function。
所以我不太明白index.js（我感觉又是跟Router一样的东西）存在的意义。

**Comment by shenjo** [comment]
当然 Layer有一点点小改动，就是构造函数部分，以及判断是否这个请求归当前Layer处理的函数。以前是只要req.method匹配就handle,现在是在此基础上path也要匹配。
Lesson3:
![image](https://user-images.githubusercontent.com/13912646/33751850-b127ee28-dc18-11e7-8f39-6dadf36a0696.png)
Lesson4:
![image](https://user-images.githubusercontent.com/13912646/33751857-c0c90114-dc18-11e7-86b4-919ef60dd7b2.png)

**Comment by sunkuo** [comment]
@shenjo 有些地方是冗余的，不是实现当前功能需要的。主要的目的是承接下文。条条大路通罗马，我是按照Express去罗马的方式写的^_^
