### ISSUE TITLE
很棒的文章但仍然有知识点没有涉及？

### ISSUE THREAD

**Issue by daniel0128** [sunkuo/grow-to-express#5]
大概跟着lesson写了一遍，对于express逐渐有了理解，然而提纲中的部分问题貌似没有涉及到？

比如：

- 严格路由和不严格路由有什么区别

- 如何设置路由不敏感或严格路由

- trust proxy什么用

- Etag weak 和strong有什么区别

- app.all和app.use的区别及性能差异

个人认为带着这些问题跟随lesson效率会更高一些，但是coding的过程中发现代码没有体现以上这些知识点？

**Comment by kaisela** [comment]
还太少吧，自己要把express重新写完可能会了解

**Comment by sunkuo** [comment]
这个项目主要是为了说明Express的原理
涉及太多细节知识，会加重这个项目的理解程度
其他的知识都有详细的讲解，我这里不再复述
谢谢关注 @daniel0128  @kaisela
